Question 1. Alexander Theophile Vandermonde Matrix

In [1]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [2]:
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

Question 2. Write a function to find moving average in an array over a window.

In [3]:
def moving_average(x, w):
    return np.convolve(x, np.ones(w), 'valid') / w
x = np.array([10,20,30,40,50,60,70,80,90,100])
moving_average(x, 4)

array([25., 35., 45., 55., 65., 75., 85.])

In [4]:
y = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
moving_average(y, 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])